apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-rajkot
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: hello-rajkot
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-rajkot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-rajkot
      tier: backend
  template:
    metadata:
      labels:
        app: hello-rajkot
        tier: backend
    spec:
      containers:
      - name: hello-container
        image: harshmanvar/golang-rajkot-demo:7a57d12
        ports:
        - containerPort: 8080