apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-rajkot
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: hello-rajkot
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello-rajkot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-rajkot
      tier: backend
  template:
    metadata:
      labels:
        app: hello-rajkot
        tier: backend
    spec:
      containers:
      - name: hello-container
        image: harshmanvar/gdg-rajkot:6571547
        ports:
        - containerPort: 3000
        readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
        livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10