## Build image
docker build --no-cache -t nodejs:v1 .
## Run the image
docker run --name nodejs -d -p 3000:3000 nodejs:v1

## Check docker logs
docker logs nodejs

## Check CPU & Memory
docker stats nodejs

## Kill Container
docker kill nodejs

## Load testing Fortio
~/go/bin/fortio server -http-port 0.0.0.0:5000
UI: http://localhost:5000/fortio/

10000/5000

## Remove all container
docker rm -f $(docker ps -aq)

## Docker repo build
docker build -t harshmanvar/gdg-rajkot:mac-build .
docker push harshmanvar/gdg-rajkot:mac-build